- .github/workflows/build-and-test-core.yml
- .github/workflows/generate-and-test-sdk.yml
- Fix Github Actions' cancellation
N/A
> chore(github): Fix Github Actions Cancellation

- .github/workflows/generate-and-test-sdk.yml
- generator/src/main/resources/templates/expediagroup-sdk/api/api.mustache
- Execute operations asynchronously
N/A
> chore(generation): Execute Operations Asynchronously

- .github/dependabot.yml
- Add Maven to dependabot.yml
N/A
> chore(dependabot): Add Maven to dependabot.yml

- .github/workflows/build-and-test-core.yml
- .github/workflows/codecov.yaml
> chore: fix codecov reports

- generator/src/main/resources/templates/expediagroup-sdk/package.mustache
- Clean unwanted generated directories
N/A
> chore(generation): Clean Unwanted Generated Directories

- core/src/authentication/Authenticator.ts
- core/src/client/Client.ts
- core/test/constant/Constant.ts
- core/test/helper/TestClient.ts
- generator/src/main/kotlin/com/expediagroup/sdk/generators/openapi/OpenApiSdkGenerator.kt
- generator/src/main/resources/templates/expediagroup-sdk/api/api.mustache
- Update the user-agent header
N/A
> chore(generation): Update The User-Agent Header

- core/src/constant/Logging.ts
- core/src/logging/LoggerProvider.ts
- core/test/logging/ExpediaGroupLogger.test.ts
- core/test/logging/LoggerProvider.test.ts
- generator/src/main/resources/templates/expediagroup-sdk/index.mustache
> chore(generation): Expose Core Exports

- generator/src/main/resources/templates/expediagroup-sdk/api/api.mustache
- generator/src/main/resources/templates/expediagroup-sdk/index.mustache
> chore(generation): Export Api Errors

- .github/workflows/generator-main.yaml
- .github/workflows/generator-publish-artifact.yaml
- Fix skipping steps that are dependent on other skipped steps (skip != failure)
N/A
> Osama salman99/fix unintended skips

- generator/src/main/kotlin/com/expediagroup/sdk/generators/openapi/MustacheHelpers.kt
- generator/src/main/resources/templates/expediagroup-sdk/api/api.mustache
- generator/src/main/resources/templates/expediagroup-sdk/error/apiError.mustache
- Throw Exceptions Per Operation
N/A
> chore(generation): Throw Exceptions Per Operation

- .github/workflows/generator-main.yaml
- .github/workflows/generator-publish-artifact.yaml
- Change workflow inputs to boolean
N/A
> chore(workflows): Change Workflow Inputs to Boolean

- .github/workflows/generator-generate.yaml
- .github/workflows/generator-publish-artifact.yaml
- .github/workflows/generator-publish-sources.yaml
- generator/src/main/resources/templates/expediagroup-sdk/package.mustache
> feat(workflows): Upload Generated Docs

- .github/dependabot.yaml
- Add generated dependencies to dependabot
N/A
> fix(dependabot): Add Generated Dependencies to Dependabot

- core/src/constant/LogMaskingRegex.ts
- core/src/logging/LogMasker.ts
- core/test/logging/LogMasker.test.ts
- Mask PCI security-sensitive information
N/A
> Mask PCI Security-Sensitive Information

- .github/workflows/build-and-test-core.yaml
- Set Codecov to fail on error
N/A
> fix(codecov): Set Codecov To Fail On Error

- .github/workflows/generator-publish-sources.yaml
- Change the directory to which the docs are published.
N/A
> fix(workflows): Change Docs Publish Directory

- .github/labeler.yml
- Fix labeler to include all docs files
N/A
> fix(workflows): Fix labeler to include all docs files

- .github/workflows/generate-and-test-sdk.yaml
- Fix dependabot workflow errors
N/A
> fix(workflows): Fix dependabot workflow errors

- .github/workflows/generate-and-test-sdk.yaml
> fix(workflows): Fix workflow errors

- core/src/authentication/Authenticator.ts
- core/src/constant/Authentication.ts
- core/src/constant/Constant.ts
- core/test/authentication/Authentication.test.ts
- Support identity auth v3
N/A
> feat(authentication): Support identity auth v3

- .github/workflows/contribution-lint.yaml
- commitlint.config.js
> feat(github): add `contrib-lint.yaml` workflow

- .github/workflows/contribution-lint.yaml
- commitlint.config.js
> feat(github): fix not latest commit only validated

- .github/workflows/contribution-lint.yaml
- package-lock.json
- package.json
- Downgrade @commitlint/config-conventional version
N/A
> fix: downgrade @commitlint/config-conventional version

- .github/workflows/generator-draft-release.yaml
- .github/workflows/generator-main.yaml
- .releaserc.json
- clean-release-tags.sh
- create-github-release.sh
- get-latest-tag.sh
- update-github-release.sh
- Clean release tags and release notes
N/A
> fix: clean release tags and release notes

- .github/workflows/build-and-test-core.yaml
> chore: disable codecov

- .github/workflows/build-and-test-core.yaml
- .github/workflows/generate-and-test-sdk.yaml
- .github/workflows/generator-draft-release.yaml
- .github/workflows/generator-generate.yaml
- .github/workflows/generator-publish-artifact.yaml
- generator/src/main/resources/templates/expediagroup-sdk/package.mustache
> chore: unify node version used in github actions

- generator/src/main/resources/dependencies/package.json
- generator/src/test/resources/exemplar-docs/client/classes/ExemplarClient.md
- generator/src/test/resources/exemplar-docs/client/core/classes/AxiosClientConfigurations.md
- generator/src/test/resources/exemplar-docs/models/classes/ErrorCause.md
- generator/src/test/resources/exemplar-docs/models/classes/Greeting.md
- generator/src/test/resources/exemplar-docs/models/classes/ModelError.md
- generator/src/test/resources/exemplar-docs/models/type-aliases/ErrorCauseLocationEnum.md
Upgrade typedoc dependencies that need to go in sync
> chore: update typedoc dependencies
